
name: build

on:

  workflow_dispatch:

jobs:

  apk:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

        with:

          ref: main

      - name: Setup Java

        uses: actions/setup-java@v4

        with:

          distribution: 'zulu'

          java-version: '17'

      - name: Setup Flutter

        uses: subosito/flutter-action@v2

        with:

          channel: 'stable'

      - name: Inject & Build

        run: |

          mkdir -p backup

          [ -f lib/main.dart ] && cp lib/main.dart backup/

          [ -f pubspec.yaml ] && cp pubspec.yaml backup/

          

          rm -rf android lib pubspec.yaml

          flutter create . --org com.royal --project-name my_cloud_compiler --platforms android --overwrite

          

          [ -f backup/main.dart ] && cp backup/main.dart lib/main.dart

          [ -f backup/pubspec.yaml ] && cp backup/pubspec.yaml pubspec.yaml

          

          flutter pub get

          flutter build apk --release --build-name=1.0.0 --build-number=${{ github.run_number }}

      - name: Upload Direct APK

        uses: actions/upload-artifact@v4

        with:

          name: release-apk

          path: build/app/outputs/flutter-apk/app-release.apk

          overwrite: true

